// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateProductParams struct {
	Name        *string  `json:"name"`
	Description *string  `json:"description"`
	Price       *float64 `json:"price"`
}

type Message struct {
	ID   string `json:"id"`
	From *User  `json:"from"`
	To   *User  `json:"to"`
	Msg  string `json:"msg"`
}

type MessageInput struct {
	ID   string     `json:"id"`
	From *UserInput `json:"from"`
	To   *UserInput `json:"to"`
	Msg  string     `json:"msg"`
}

type Product struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
}

type Response struct {
	Message *string `json:"message"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type UserInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
